version: '3'
services:
  my_db: # БД PostgreSQL
    image: postgres:latest # Берём оф. образ PostgreSQL
    volumes:
      - ${POSTGRES_VOLUME_PATH}:/var/lib/postgresql/ # Сохраняем все данные БД в ФС хоста
    env_file: # Указываем явно путь к файлу с переменными окружения
      - .env
    environment: # Переменные окружения для создания юзера, пароля и БД в postgres
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
      - mynetwork
  fastapi_app: # FastAPI приложение
    build: # Собираем контейнер из Dockerfile
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    entrypoint: ["/fastapi_app/entrypoint.sh"]
    ports:
      - "8000:8000" # Связываем 8000 порт хоста с 8000 портом контейнера в приложением Django
    volumes: # Устанавливаем место для хранилища файлов
      - ${FASTAPI_APP_PATH}:/fastapi_app # Связываем текущую директорию с папкой проекта в контейнере
    depends_on: # Указываем, что этот контейнер должен запуститься после контейнеров: db
      - my_db
    networks:
      - mynetwork
networks:
  mynetwork: